#pragma once

#include <QString>
#include <QStringList>

namespace granger {

struct InternalPageContext {
    QString homeUrl;
    QString proxyUrl;
    QString proxyState;
    QString proxyRestartState;
    QString networkMode;
    QString currentRoute;
    QString currentIp;
    QString torState;
    QString bridgeState;
    QString bridgeBootstrap;
    QString bridgeError;
    QString bridgeTorrcPath;
    QString torExecutable;
    QString externalTorSocksUrl;
    QString upstreamProxyUrl;
    QString upstreamProxyUsername;
    QString torCurrentStrategy;
    QString torTransport;
    QString torSystemProxyStatus;
    QString torTunnelStatus;
    QString torLocalProxyStatus;
    QString torIpv4Status;
    QString torIpv6Status;
    QString torConflictCode;
    QString torConflictSummary;
    QString torRecommendedAction;
    bool torConflictWarning = false;
    QString language;
    QString searchImplementation;
    QString resultsPath;
    QString reportPath;
    QString message;
    QString homeBackgroundDataUrl;
    QString homeAiIconDataUrl;
    QString homeSearchEngineIconDataUrl;
    QString homeRouteStatus;
    QString homeRouteVisualState;
    QString homeRouteTooltip;
    QString bridgeProfilesHtml;
    QString bridgeTorrcSnippet;
    QString resultsHtml;
    QString resultsQuery;
    QString resultsMode;
    QString downloadsHtml;
    QString cookiesHtml;
    QString cookieFilter;
    QString bookmarksHtml;
    QString historyHtml;
    QString siteInfoHtml;
    QString containersHtml;
    QString containerSiteRulesHtml;
    QString containerOptionsHtml;
    QString pampReportHtml;
    QString routeState;
    QString routeError;
    QString settingsCategory;
    QString defaultSearchEngineId;
    QString defaultSearchEngineName;
    QString searchEngineOptionsHtml;
    QString enabledSearchEnginesHtml;
    QString userAgentProfile;
    QString customUserAgent;
    QString webGlProtectionMode;
    QString canvasProtectionMode;
    QString audioProtectionMode;
    QString screenExposureMode;
    QString timezoneMode;
    QString hardwareExposureMode;
    QString windowSizeProtectionMode;
    QString fingerprintEffectiveWebGlMode;
    QString fingerprintEffectiveCanvasMode;
    QString fingerprintEffectiveAudioMode;
    QString fingerprintEffectiveScreenMode;
    QString fingerprintEffectiveTimezoneMode;
    QString fingerprintEffectiveHardwareMode;
    QString fingerprintEffectiveFontMode;
    QString fingerprintEffectiveClientHintsMode;
    QString localLogMode;
    QStringList localLogCategories;
    int localLogRetentionDays = 7;
    int localLogMaxMiB = 2;
    int localLogMaxFiles = 3;
    bool clearLocalLogsOnStartup = false;
    bool clearLocalLogsOnExit = false;
    QString developerToolsDockPosition;
    QString dataRoot;
    QString profileRoot;
    QString applicationVersion;
    QString privacyPreset;
    QString activePrivacyProfile;
    QString privacyProfileOptionsHtml;
    QString privacySiteRulesHtml;
    QString privacyPermissionsHtml;
    QString privacyImportPreviewHtml;
    QString privacyDiagnosticsHtml;
    QString reportsLogsHtml;
    QString contentBlockingMode;
    QString contentBlockingAllowlistHtml;
    QString contentBlockingDomainPoliciesHtml;
    QString contentBlockingRecentEventsHtml;
    QString httpsFirstMode;
    QString httpsFirstExceptionsHtml;
    int contentBlockingNetworkRuleCount = 0;
    int contentBlockingCosmeticRuleCount = 0;
    int contentBlockedRequestCount = 0;
    int contentBlockingSourceCount = 0;
    int cookieCount = 0;
    QString contentBlockingLastUpdate;
    bool contentBlockingUpdateInProgress = false;
    bool cookieInventoryLoading = false;
    bool cookieDeleteConfirmation = false;
    bool reducedMotion = false;
    bool proxyEnabled = false;
    bool antiTelemetryEnabled = true;
    bool blockPopupsEnabled = true;
    bool blockThirdPartyCookiesEnabled = false;
    bool contentBlockAdsEnabled = true;
    bool contentBlockTrackersEnabled = true;
    bool contentBlockCryptominingEnabled = true;
    bool contentBlockSocialEnabled = false;
    bool contentBlockCosmeticEnabled = true;
    bool contentBlockRegionalEnabled = false;
    bool blockInsecureFallbackEnabled = false;
    bool warnHttpFormsEnabled = true;
    bool upgradeMixedContentEnabled = true;
    bool showInsecureConnectionWarningEnabled = true;
    bool rememberHttpExceptionsEnabled = true;
    bool searchSuggestionsEnabled = false;
    bool showSearchEngineIcon = true;
    bool sidebarPinned = false;
    bool developerToolsEnabled = true;
    bool developerToolsOpenWithF12 = true;
    bool developerToolsAllowInspect = true;
    bool developerToolsDisabledInPrivateProfiles = true;
    bool developerToolsAllowInternalPages = false;
    bool privacyJavascriptEnabled = true;
    bool fingerprintProtectionEnabled = true;
    bool fingerprintEffectiveLetterboxing = false;
    bool fingerprintEffectiveSpeechMediaRestricted = false;
    bool webRtcLeakProtectionEnabled = true;
    bool trackerBlockingEnabled = true;
    bool privacyBlockThirdPartyCookies = true;
    bool privacyBlockThirdPartyScripts = false;
    bool privacyBlockThirdPartyFrames = false;
    bool privacyBlockWebAssembly = false;
    bool privacyBlockPopups = true;
    bool privacyDisablePrefetch = true;
    bool privacyDisableHyperlinkAuditing = true;
    bool privacyRestrictReferrer = true;
    bool globalPrivacyControlEnabled = true;
    bool doNotTrackEnabled = false;
    bool stripTrackingParametersEnabled = true;
    bool resolveTrackingRedirectsEnabled = true;
    bool clearCookiesOnExit = false;
    bool clearCacheOnExit = false;
    bool clearStorageOnExit = false;
    bool torSessionIsolation = true;
    bool clearTorOnDisconnect = true;
    bool blockDirectFallback = true;
    bool disableWebRtcInTor = true;
    bool onionClearnetIsolation = true;
    QString wipeConfirmationPhrase;
    bool wipeConfirmationStage = false;
    bool wipeDeleteDownloads = false;
    int trackedDownloadCount = 0;
};

class InternalPages final {
public:
    static QString titleFor(const QString &address);
    static QString supportAddress(const QString &id);
    static QString supportCryptoBotUrl();
    static QString supportCryptoBotQrUrl();
    static QString granger(const InternalPageContext &context, const QString &query = QString());
    static QString privacy(const InternalPageContext &context);
    static QString tor(const InternalPageContext &context);
    static QString bridges(const InternalPageContext &context);
    static QString settings(const InternalPageContext &context);
    static QString network(const InternalPageContext &context);
    static QString reports(const InternalPageContext &context);
    static QString downloads(const InternalPageContext &context);
    static QString cookies(const InternalPageContext &context);
    static QString bookmarks(const InternalPageContext &context);
    static QString history(const InternalPageContext &context);
    static QString siteInfo(const InternalPageContext &context);
    static QString siteAnalysis(const InternalPageContext &context);
    static QString searchResults(const InternalPageContext &context);
    static QString simple(const QString &title, const QString &subtitle, const QString &body);
};

}
